baseurl = "https://support.wethod.com/"
canonifyurls = true
googleAnalytics = ""
languageCode = "en-us"
metadataformat = "yaml"
theme = "hugo-material-docs"
title = "WETHOD / Learning Center"
# Configure draft pages
buildDrafts = false  # Ignores the pages in draft from the build
draft = false       # Default value
[blackfriday]
fractions = true
plainIDAnchors = true
smartDashes = true
smartypants = true
[[menu.company]]
name = "Data Freezing Engine"
url = "data-freezing-engine/index/"
weight = 11
[[menu.company]]
name = "Order Plan"
url = "order-plan/index/"
weight = 10
[[menu.company]]
name = "Invoice Plan"
url = "invoice-plan/index/"
weight = 9
[[menu.company]]
name = "Capex"
url = "capex/index/"
weight = 8
[[menu.company]]
name = "Marketing"
url = "marketing/index/"
weight = 7
[[menu.company]]
name = "G & A"
url = "general-admin/index/"
weight = 6
[[menu.company]]
name = "Payroll"
url = "payroll/index/"
weight = 5
[[menu.company]]
name = "Gross Margin"
url = "gross-margin/index/"
weight = 4
[[menu.company]]
name = "External Costs"
url = "external-costs/index/"
weight = 3
[[menu.company]]
name = "Revenues"
url = "revenues/index/"
weight = 2
[[menu.company]]
name = "Profit & Loss"
url = "profit-loss/index/"
weight = 1
[[menu.group]]
name = "Setup"
url = "group-setup/index/"
weight = 3
[[menu.group]]
name = "Revenues"
url = "group-revenues/index/"
weight = 2
[[menu.group]]
name = "Profit & Loss"
url = "group-profit-loss/index/"
weight = 1
[[menu.main]]
name = "Settings"
url = "settings/index/"
weight = 11
[[menu.main]]
name = "Finance"
url = "finance/index/"
weight = 10
[[menu.main]]
name = "Reports"
url = "reports/index/"
weight = 9
[[menu.main]]
name = "Friday"
url = "friday/index/"
weight = 8
[[menu.main]]
name = "Planning"
url = "planning/index/"
weight = 7
[[menu.main]]
name = "Budget"
url = "budget/index/"
weight = 6
[[menu.main]]
name = "Pipeline"
url = "pipeline/index/"
weight = 5
[[menu.main]]
name = "Alerts"
url = "alerts/index/"
weight = 4
[[menu.main]]
name = "Dashboard"
url = "dashboard/index/"
weight = 3
[[menu.main]]
name = "Desk"
url = "desk/index/"
weight = 2
[[menu.main]]
name = "Getting started"
url = "getting-started/index/"
weight = 1
[[menu.other]]
name = "Glossary"
url = "glossary/index/"
weight = 2
[[menu.other]]
name = "FAQ"
url = "faq/index/"
weight = 1
[params]
author = "Andrea Tombolato"
copyright = ""
custom_css = ["stylesheets/variables.css", "stylesheets/custom-style.css"]
custom_js = []
description = "A lean multi-project management platform that fosters the autonomy and ownership of every team member at any level."
favicon = "images/favicon.ico"
highlight_css = ""
logo = "images/logo.png"
permalink = "#"
provider = ""
repo_url = ""
version = ""
GoogleAnalytics = "UA-105754515-1"
[params.font]
code = "Rubik"
text = "Rubik"
[params.palette]
accent = "teal"
primary = "black"
[params.Social]
email = "info@wethod.com"
github = ""
twitter = ""
