# Build with Hugo and deploy to GitHub page

name: Hugo build & publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-24.04
    env:
      TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
      TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.20.4'

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Debug steps to help diagnose npm install issues
      - name: Debug environment
        run: |
          echo "=== Node & npm version ==="
          node -v
          npm -v

          echo "=== npm registry ==="
          npm config get registry

          echo "=== npm config list ==="
          npm config list

          echo "=== Searching for .npmrc files ==="
          find . -name ".npmrc" -exec echo "Found: {}" \; -exec cat {} \;

          echo "=== Current working dir ==="
          pwd
          ls -la

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - run: rm ./public/admin/.gitignore

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: wethod/wethod.github.io
          publish_branch: master
          publish_dir: ./public
